# Generated by Django 4.0.4 on 2022-05-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='lesson',
            field=models.CharField(default='Default', max_length=50),
        ),
    ]
